### PR TITLE
Bump to 3.0.0

### PR DESCRIPTION
**Pull request by jturel**
I think it's a good time to do a release and get this out to players in time for BFA. Due to breaking API changes a major  version bump seems right to me.

### CODE REVIEW

**Comment by wardz** [comment]
There's currently a bug with sArena's savedvariables, causing them to duplicate and save gibberish (userdata) values. [(pastebin)](https://pastebin.com/TvkTHX2w)
My sArena's savedvariables file is currently 397kb, 13727 lines long and keeps growing. Probably want to have this fixed first before releasing.

I also noticed there's a minor taint issue when trying to move(?) the arena frames in combat. For example, if an enemy rogue comes out of stealth while you're in combat, this causes the arena frame to be moved if it was not shown at arena start already, and thus causes UI taint. I think this taint only happens the first time the frames are moved/shown but not sure. Don't think this happened in Legion.

**Comment by jturel** [comment]
@wardz did you see this happening on the latest version in this repo or the version on curse? Haven't seen this myself!

**Comment by wardz** [comment]
Both versions. Just noticed it happens when dragging the trinket icon in testmode, if you drag the arena frame itself it doesn't bug out. I'm using mirrored frames + simple arena frames, just incase this matters.

If you do /dump sArenaDB after dragging the trinket icon frame you'll see it tries to set data such as:
`manatextright = {
  [0] = <userdata ArenaEnemyFrame3ManaBarTextRight[0]>
},
`

**Comment by stako** [comment]
The versioning has historically been quite arbitrary for sArena. Perhaps now is a good time to set some guidelines for it. I like Blizzards format:

- The versioning uses 3 numbers (eg. 1.4.3)
- First number increases when a major update is made
- Second number increases when a new feature is added
- Third number increases when maintenance is done

In keeping with these guidelines, the recent commits for BFA would merit a change in the third number.

I've marked @jturel as a collaborator. He can push commits to the repo as he sees fit. I've also enabled the 'issues' portal to report bugs.

**Comment by jturel** [comment]
I was thinking more along the lines of semantic versioning: https://semver.org/ which would have been a major version bump - but semver is only loosely applicable here anyway.

Thanks for the collaborator access! Since I'm not an addon developer I still intend to create pull requests for peer review since I don't want to introduce anything unwanted or broken into the addon. Happy to review submissions from others too.

**Comment by jturel** [comment]
@stako I'd like to not lose track of the problem that @wardz mentioned - though I don't think we need to block releasing the recent fixes. Do you think we should enable the issue tracker here on github? The comments section on Curse doesn't seem like the best place to track.

**Pull request closed without merging**
