### PR TITLE
Add Living Honey hex aura

### PR DESCRIPTION
**Pull request by fsouzadi1995**
[Link to spell](https://www.wowhead.com/spell=309328/hex)

### CODE REVIEW

**Comment by fsouzadi1995** [comment]
@stako any reason over why this got closed?

**Comment by stako** [comment]
Did you delete your fork? If yes, this PR was likely automatically closed when your fork was deleted.

**Comment by fsouzadi1995** [comment]
@stako that was probably it then, thank you!

**Comment by fsouzadi1995** [comment]
> Did you delete your fork? If yes, this PR was likely automatically closed when your fork was deleted.

that was probably it then, thank you!

**Pull request merged**
